def get_about_text():
    about = f"""
    <div class="aboutSection padding lightBackground border offset offsetTop offsetBottom">
    <h1 class="removeOffsetTop">Recipes</h1>
    <p>Completely plagiarised from Finn (justmy.cooking) - thank you Finn!</p>
    <p>These are just a combination of my own recipes and ones I have in my collection from my assortment of cookbooks.</p>
    <p>I wanted a place to store and share things easily, and this is an easy way for me to do that.</p>
    </div>
    <div class="aboutSection padding lightBackground border offset offsetTop offsetBottom">
    <h1 class="removeOffsetTop">Finn's Technical Comments</h1>
    <p>
        For those interested in the technical, Just My Cooking is actually the 4th attempt at making a recipe webiste for me. Each one before this has been lacking in features or maintainability. I've used Ghost CMS and Wordpress previously but found them clunky and difficult to achieve what I wanted.
        Instead... I've written my own CMS, kind of. This whole webiste is made up of static HTML pages, css and a touch of JS for search and random recipes. The HTML and JS are all generated by a Python script from a series of json files containing recipes in the recipe schema format.
    </p>
    <p>
        Why would I do this? Well, I believe the modern internet with all of its standards and javascript frameworks is needlessly complicated and clunky. It makes starting a basic recipe website, blog or informational page difficult without using some out of the box site builder like squarespace.
        You have to bend a CMS that has been built to do everything (not well) to your will which is painful and frustrating. You have to update things to ensure security, and when you do you risk breaking features, causing incompatability problems, you risk fucking everything up.
    </p>
    <p>    
        If you build something using a javascript framework you have to manage compatability issues, the risk of them no longer being supported, and create something far more complex than it needs to be.
        If you use a paid service you often lose flexability on the free tiers, or you pay more than it would cost to host it yourself.
        Instead, by keeping it static I can host this wherever I want, I can just run it on my laptop if I want to! Simple. As it should be.
    </p>
    </div>
    """
    return about
    
